PRAGMA enable_profiling='json';
PRAGMA profile_output='_tmp_profiles/0_profile.json';
.read imdb/benchmarks/ceb/10a/ff5392412c047db440be1c25a9368dca0af322a6.sql
PRAGMA profile_output='_tmp_profiles/1_profile.json';
.read imdb/benchmarks/ceb/10a/7bcc6d0a7d4f71732a63dd7ed1fa90b920521629.sql
PRAGMA profile_output='_tmp_profiles/2_profile.json';
.read imdb/benchmarks/ceb/4a/4a482.sql
PRAGMA profile_output='_tmp_profiles/3_profile.json';
.read imdb/benchmarks/ceb/4a/4a129.sql
PRAGMA profile_output='_tmp_profiles/4_profile.json';
.read imdb/benchmarks/job/18c.sql
PRAGMA profile_output='_tmp_profiles/5_profile.json';
.read imdb/benchmarks/job/8a.sql
PRAGMA profile_output='_tmp_profiles/6_profile.json';
.read imdb/benchmarks/job/10b.sql
PRAGMA profile_output='_tmp_profiles/7_profile.json';
.read imdb/benchmarks/ceb/4a/4a211.sql
PRAGMA profile_output='_tmp_profiles/8_profile.json';
.read imdb/benchmarks/ceb/4a/4a211.sql
PRAGMA profile_output='_tmp_profiles/9_profile.json';
.read imdb/benchmarks/job/10c.sql
PRAGMA profile_output='_tmp_profiles/10_profile.json';
.read imdb/benchmarks/job/18b.sql
PRAGMA profile_output='_tmp_profiles/11_profile.json';
.read imdb/benchmarks/job/10a.sql
PRAGMA profile_output='_tmp_profiles/12_profile.json';
.read imdb/benchmarks/ceb/4a/4a110.sql
PRAGMA profile_output='_tmp_profiles/13_profile.json';
.read imdb/benchmarks/ceb/8a/8a105.sql
PRAGMA profile_output='_tmp_profiles/14_profile.json';
.read imdb/benchmarks/job/8b.sql
PRAGMA profile_output='_tmp_profiles/15_profile.json';
.read imdb/benchmarks/ceb/8a/8a22.sql
PRAGMA profile_output='_tmp_profiles/16_profile.json';
.read imdb/benchmarks/ceb/6a/6a19.sql
PRAGMA profile_output='_tmp_profiles/17_profile.json';
.read imdb/benchmarks/ceb/6a/6a337.sql
PRAGMA profile_output='_tmp_profiles/18_profile.json';
.read imdb/benchmarks/ceb/6a/6a305.sql
PRAGMA profile_output='_tmp_profiles/19_profile.json';
.read imdb/benchmarks/ceb/6a/6a305.sql
PRAGMA profile_output='_tmp_profiles/20_profile.json';
.read imdb/benchmarks/ceb/6a/6a532.sql
PRAGMA profile_output='_tmp_profiles/21_profile.json';
.read imdb/benchmarks/ceb/4a/4a137.sql
PRAGMA profile_output='_tmp_profiles/22_profile.json';
.read imdb/benchmarks/ceb/4a/4a222.sql
PRAGMA profile_output='_tmp_profiles/23_profile.json';
.read imdb/benchmarks/job/8d.sql
PRAGMA profile_output='_tmp_profiles/24_profile.json';
.read imdb/benchmarks/job/17a.sql
PRAGMA profile_output='_tmp_profiles/25_profile.json';
.read imdb/benchmarks/job/8c.sql
PRAGMA profile_output='_tmp_profiles/26_profile.json';
.read imdb/benchmarks/ceb/10a/d4eec8b3940f97bddc1b30930d723b9b1245aee9.sql
PRAGMA profile_output='_tmp_profiles/27_profile.json';
.read imdb/benchmarks/job/17d.sql
PRAGMA profile_output='_tmp_profiles/28_profile.json';
.read imdb/benchmarks/ceb/4a/4a340.sql
PRAGMA profile_output='_tmp_profiles/29_profile.json';
.read imdb/benchmarks/ceb/10a/b0fa6a3f8fa1820a4f7be7aeb6b405909834053c.sql
PRAGMA profile_output='_tmp_profiles/30_profile.json';
.read imdb/benchmarks/job/18a.sql
PRAGMA profile_output='_tmp_profiles/31_profile.json';
.read imdb/benchmarks/ceb/10a/4f19c56e1f0ccdeca925474a607fb0d9994532ff.sql
PRAGMA profile_output='_tmp_profiles/32_profile.json';
.read imdb/benchmarks/ceb/4a/4a143.sql
